# Generated by Django 4.2.9 on 2024-01-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='developer',
            new_name='is_developer',
        ),
    ]
