# Generated by Django 4.2.9 on 2024-01-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_developer_user_is_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.CharField(default='127.0.0', max_length=255),
            preserve_default=False,
        ),
    ]
