# Generated by Django 4.2.9 on 2024-01-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='denied_ip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
