# Generated by Django 4.2.9 on 2024-01-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
