# Generated by Django 4.2.9 on 2024-01-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('engine', models.CharField(choices=[('mysql', 'mysql'), ('postgresql', 'postgresql'), ('mssql+pyodbc', 'mssql+pyodbc'), ('cx_oracle', 'cx_orcle'), ('mariadb', 'mariadb'), ('mysql_aurora', 'mysql_aurora'), ('mysql+mysqldb', 'mysql+mysqldb')], max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('database', models.CharField(max_length=50)),
                ('parameters', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
