# Generated by Django 4.2.9 on 2024-01-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_databaseconfig_database_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='url',
            field=models.URLField(default='mysql://olusola:ayomide@ibram:400/user'),
            preserve_default=False,
        ),
    ]
