# Generated by Django 4.2.9 on 2024-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_databaseconfig_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='base_url',
            field=models.URLField(default='mysql://olusola:ayomide@ibram:400/'),
            preserve_default=False,
        ),
    ]
