# Generated by Django 4.2.9 on 2024-01-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_databaseconfig_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission',
            field=models.CharField(choices=[('read', 'read'), ('read-edit', 'read-edit'), ('read-edit-create', 'read-edit-create'), ('read-edit-create-delete', 'read-edit-create-delete')], default='read', max_length=255),
        ),
    ]
