# Generated by Django 4.2.9 on 2024-01-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_permission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='table_whitelist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='base_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
