# Generated by Django 4.2.9 on 2024-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_databaseconfig_table_whitelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconfig',
            name='base_url',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='databaseconfig',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
