# Generated by Django 4.2.9 on 2024-03-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_databaseconfig_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconfig',
            name='base_url',
            field=models.CharField(max_length=255),
        ),
    ]
