# Generated by Django 4.2.9 on 2024-01-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='denied_ip',
        ),
    ]
