# Generated by Django 4.2.9 on 2024-03-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_profile_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='github',
        ),
    ]
