# Generated by Django 4.2.9 on 2024-03-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0009_profile_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
