# Generated by Django 4.2.9 on 2024-03-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_term',
            field=models.BooleanField(default=False),
        ),
    ]
