# Generated by Django 4.2.9 on 2024-03-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0014_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_search',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default='BGYUpvoHfWpDXGSajPB7cCXecRqpAFkmHyYGK032', max_length=100, unique=True),
        ),
    ]
