# Generated by Django 4.2.9 on 2024-04-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0018_alter_emailverificationtoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default='jyUsrimXrkgDe8A27tnakkcbYt9d0MOu24UK7r0Q', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedIn',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stackoverflow',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
